web:
  image: adalessa/laravel-container:5.6
  ports:
    - "5000:80"
  volumes:
    - ./code:/var/www/html
  links:
    - mysql
mysql:
  image: mysql:5.6
  env_file: mysql.env
  ports:
   - "4306:3306"
